### ISSUE TITLE
Any further progress?

### ISSUE THREAD

**Issue by strich** [Frager/CA-Fluid-Simulation#1]
Hi guys,

Really interesting project - Thanks for providing the code for review! I was just wondering if you took it any further since you submitted it? Have you applied it in any particular projects?

**Comment by Destolos** [comment]
Hello,  thanks you for interest. The project is completed (Link to paper: https://dl.acm.org/citation.cfm?id=3143415) and we will not continue to work on it. We used an early prototype of the simulation in an unpublished student-project, but besides this, we didn't use it.

**Comment by strich** [comment]
Unfortunately the paper is paywalled on that site. Is it available for free anywhere? (I don't know much about universities and paper outputs)

**Comment by Destolos** [comment]
I don't know whether there is a free version, but perhaps the link on this site will work: http://st.sigchi.org/publications/toc/vrst-2017.html
